# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kisun\Desktop\new2020.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.global_source_label = QtWidgets.QLabel(self.centralwidget)
        self.global_source_label.setObjectName("global_source_label")
        self.horizontalLayout_2.addWidget(self.global_source_label)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.global_cvtime_label = QtWidgets.QLabel(self.centralwidget)
        self.global_cvtime_label.setObjectName("global_cvtime_label")
        self.horizontalLayout_2.addWidget(self.global_cvtime_label)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.global_lag_label = QtWidgets.QLabel(self.centralwidget)
        self.global_lag_label.setObjectName("global_lag_label")
        self.horizontalLayout_2.addWidget(self.global_lag_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.connect_raspi_button = QtWidgets.QPushButton(self.groupBox_2)
        self.connect_raspi_button.setMinimumSize(QtCore.QSize(181, 51))
        self.connect_raspi_button.setObjectName("connect_raspi_button")
        self.horizontalLayout_4.addWidget(self.connect_raspi_button)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.socket_def_save_button = QtWidgets.QPushButton(self.groupBox_2)
        self.socket_def_save_button.setObjectName("socket_def_save_button")
        self.gridLayout_3.addWidget(self.socket_def_save_button, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.socket_def_use_button = QtWidgets.QPushButton(self.groupBox_2)
        self.socket_def_use_button.setObjectName("socket_def_use_button")
        self.gridLayout_3.addWidget(self.socket_def_use_button, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.connect_gsheets_button = QtWidgets.QPushButton(self.groupBox_3)
        self.connect_gsheets_button.setMinimumSize(QtCore.QSize(181, 51))
        self.connect_gsheets_button.setObjectName("connect_gsheets_button")
        self.horizontalLayout_5.addWidget(self.connect_gsheets_button)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 0, 1, 1, 3)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.open_db_button = QtWidgets.QPushButton(self.groupBox_4)
        self.open_db_button.setMinimumSize(QtCore.QSize(181, 0))
        self.open_db_button.setObjectName("open_db_button")
        self.verticalLayout_7.addWidget(self.open_db_button)
        self.connect_db_button = QtWidgets.QPushButton(self.groupBox_4)
        self.connect_db_button.setMinimumSize(QtCore.QSize(181, 0))
        self.connect_db_button.setObjectName("connect_db_button")
        self.verticalLayout_7.addWidget(self.connect_db_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 4, 1, 1)
        self.last_read_label = QtWidgets.QLabel(self.tab_4)
        self.last_read_label.setObjectName("last_read_label")
        self.gridLayout_2.addWidget(self.last_read_label, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 2, 1, 1)
        self.queue_size_label = QtWidgets.QLabel(self.tab_4)
        self.queue_size_label.setObjectName("queue_size_label")
        self.gridLayout_2.addWidget(self.queue_size_label, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.lag_time_label = QtWidgets.QLabel(self.tab_4)
        self.lag_time_label.setObjectName("lag_time_label")
        self.gridLayout_2.addWidget(self.lag_time_label, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.reading_label = QtWidgets.QLabel(self.tab_4)
        self.reading_label.setObjectName("reading_label")
        self.gridLayout_2.addWidget(self.reading_label, 0, 1, 1, 1)
        self.failed_attempts_label = QtWidgets.QLabel(self.tab_4)
        self.failed_attempts_label.setObjectName("failed_attempts_label")
        self.gridLayout_2.addWidget(self.failed_attempts_label, 0, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 4, 1, 1)
        self.heal_attempts_label = QtWidgets.QLabel(self.tab_4)
        self.heal_attempts_label.setObjectName("heal_attempts_label")
        self.gridLayout_2.addWidget(self.heal_attempts_label, 1, 5, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_11.addWidget(self.label_26)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_7.setMinimumSize(QtCore.QSize(331, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_8.setMinimumSize(QtCore.QSize(331, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_9.addWidget(self.label_28)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_8.addWidget(self.label_29)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_8.addWidget(self.lineEdit_12)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_8.addWidget(self.label_30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_19.setMinimumSize(QtCore.QSize(331, 51))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_9.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_20.setMinimumSize(QtCore.QSize(331, 51))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_9.addWidget(self.pushButton_20)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_11.addWidget(self.label_34)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_31 = QtWidgets.QLabel(self.groupBox_10)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 2, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_6.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 2, 1, 2)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_6.addWidget(self.lineEdit_14, 3, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_6.addWidget(self.lineEdit_15, 2, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_10)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 0, 0, 1, 2)
        self.horizontalLayout_11.addLayout(self.gridLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.verticalLayout_11.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_1)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_3 = QtWidgets.QWidget(self.tab_5)
        self.widget_3.setGeometry(QtCore.QRect(10, 0, 561, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 0, 0, 1, 2)
        self.label_50 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 0, 2, 1, 2)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_75 = QtWidgets.QLabel(self.tab_7)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_27.addWidget(self.label_75)
        self.label_128 = QtWidgets.QLabel(self.tab_7)
        self.label_128.setObjectName("label_128")
        self.verticalLayout_27.addWidget(self.label_128)
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_27.addWidget(self.label_37)
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_27.addWidget(self.label_42)
        self.gridLayout_9.addLayout(self.verticalLayout_27, 1, 0, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.hdop_label = QtWidgets.QLabel(self.tab_7)
        self.hdop_label.setObjectName("hdop_label")
        self.verticalLayout_28.addWidget(self.hdop_label)
        self.satellite_label = QtWidgets.QLabel(self.tab_7)
        self.satellite_label.setObjectName("satellite_label")
        self.verticalLayout_28.addWidget(self.satellite_label)
        self.total_vectors_label = QtWidgets.QLabel(self.tab_7)
        self.total_vectors_label.setObjectName("total_vectors_label")
        self.verticalLayout_28.addWidget(self.total_vectors_label)
        self.total_distance_label = QtWidgets.QLabel(self.tab_7)
        self.total_distance_label.setObjectName("total_distance_label")
        self.verticalLayout_28.addWidget(self.total_distance_label)
        self.gridLayout_9.addLayout(self.verticalLayout_28, 1, 1, 1, 1)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_29.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_29.addWidget(self.label_36)
        self.label_46 = QtWidgets.QLabel(self.tab_7)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_29.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.tab_7)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_29.addWidget(self.label_47)
        self.gridLayout_9.addLayout(self.verticalLayout_29, 1, 2, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.this_read_vectors_label = QtWidgets.QLabel(self.tab_7)
        self.this_read_vectors_label.setObjectName("this_read_vectors_label")
        self.verticalLayout_30.addWidget(self.this_read_vectors_label)
        self.this_read_distance_label = QtWidgets.QLabel(self.tab_7)
        self.this_read_distance_label.setObjectName("this_read_distance_label")
        self.verticalLayout_30.addWidget(self.this_read_distance_label)
        self.instantaneous_speed_label = QtWidgets.QLabel(self.tab_7)
        self.instantaneous_speed_label.setObjectName("instantaneous_speed_label")
        self.verticalLayout_30.addWidget(self.instantaneous_speed_label)
        self.moving_average_speed_label = QtWidgets.QLabel(self.tab_7)
        self.moving_average_speed_label.setObjectName("moving_average_speed_label")
        self.verticalLayout_30.addWidget(self.moving_average_speed_label)
        self.gridLayout_9.addLayout(self.verticalLayout_30, 1, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        self.label_43.setObjectName("label_43")
        self.verticalLayout.addWidget(self.label_43)
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setObjectName("label_41")
        self.verticalLayout.addWidget(self.label_41)
        self.label_51 = QtWidgets.QLabel(self.tab_8)
        self.label_51.setObjectName("label_51")
        self.verticalLayout.addWidget(self.label_51)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pitch_label = QtWidgets.QLabel(self.tab_8)
        self.pitch_label.setObjectName("pitch_label")
        self.verticalLayout_2.addWidget(self.pitch_label)
        self.roll_label = QtWidgets.QLabel(self.tab_8)
        self.roll_label.setObjectName("roll_label")
        self.verticalLayout_2.addWidget(self.roll_label)
        self.yaw_label = QtWidgets.QLabel(self.tab_8)
        self.yaw_label.setObjectName("yaw_label")
        self.verticalLayout_2.addWidget(self.yaw_label)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.widget_4 = QtWidgets.QWidget(self.tab_8)
        self.widget_4.setMinimumSize(QtCore.QSize(390, 280))
        self.widget_4.setObjectName("widget_4")
        self.label_55 = QtWidgets.QLabel(self.widget_4)
        self.label_55.setGeometry(QtCore.QRect(120, 110, 131, 61))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_13.addWidget(self.widget_4)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 0, 0, 1, 5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.section_label = QtWidgets.QLabel(self.tab_1)
        self.section_label.setMinimumSize(QtCore.QSize(0, 32))
        self.section_label.setObjectName("section_label")
        self.verticalLayout_20.addWidget(self.section_label)
        self.page_label = QtWidgets.QLabel(self.tab_1)
        self.page_label.setMinimumSize(QtCore.QSize(0, 32))
        self.page_label.setObjectName("page_label")
        self.verticalLayout_20.addWidget(self.page_label)
        self.gridLayout_7.addLayout(self.verticalLayout_20, 7, 1, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_95 = QtWidgets.QLabel(self.tab_1)
        self.label_95.setMinimumSize(QtCore.QSize(0, 32))
        self.label_95.setObjectName("label_95")
        self.verticalLayout_23.addWidget(self.label_95)
        self.label_96 = QtWidgets.QLabel(self.tab_1)
        self.label_96.setMinimumSize(QtCore.QSize(0, 32))
        self.label_96.setObjectName("label_96")
        self.verticalLayout_23.addWidget(self.label_96)
        self.gridLayout_7.addLayout(self.verticalLayout_23, 7, 0, 1, 1)
        self.obstacle_full_name_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_full_name_label.setMinimumSize(QtCore.QSize(0, 32))
        self.obstacle_full_name_label.setObjectName("obstacle_full_name_label")
        self.gridLayout_7.addWidget(self.obstacle_full_name_label, 1, 0, 1, 2)
        self.open_obstacles_button = QtWidgets.QPushButton(self.tab_1)
        self.open_obstacles_button.setObjectName("open_obstacles_button")
        self.gridLayout_7.addWidget(self.open_obstacles_button, 4, 0, 1, 2)
        self.obstacle_label_large = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.obstacle_label_large.setFont(font)
        self.obstacle_label_large.setAlignment(QtCore.Qt.AlignCenter)
        self.obstacle_label_large.setObjectName("obstacle_label_large")
        self.gridLayout_7.addWidget(self.obstacle_label_large, 0, 1, 1, 1)
        self.open_guidebook_button = QtWidgets.QPushButton(self.tab_1)
        self.open_guidebook_button.setObjectName("open_guidebook_button")
        self.gridLayout_7.addWidget(self.open_guidebook_button, 5, 0, 1, 2)
        self.obstacle_point_value_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_point_value_label.setMinimumSize(QtCore.QSize(0, 32))
        self.obstacle_point_value_label.setObjectName("obstacle_point_value_label")
        self.gridLayout_7.addWidget(self.obstacle_point_value_label, 3, 0, 1, 2)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_1)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(50, 50))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_7.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 8, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 5, 1, 2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_86 = QtWidgets.QLabel(self.tab_1)
        self.label_86.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_19.addWidget(self.label_86)
        self.label_74 = QtWidgets.QLabel(self.tab_1)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_19.addWidget(self.label_74)
        self.label_114 = QtWidgets.QLabel(self.tab_1)
        self.label_114.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_114.setObjectName("label_114")
        self.verticalLayout_19.addWidget(self.label_114)
        self.label_116 = QtWidgets.QLabel(self.tab_1)
        self.label_116.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_116.setObjectName("label_116")
        self.verticalLayout_19.addWidget(self.label_116)
        self.gridLayout_8.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.latitude_label = QtWidgets.QLabel(self.tab_1)
        self.latitude_label.setObjectName("latitude_label")
        self.verticalLayout_24.addWidget(self.latitude_label)
        self.longitude_label = QtWidgets.QLabel(self.tab_1)
        self.longitude_label.setObjectName("longitude_label")
        self.verticalLayout_24.addWidget(self.longitude_label)
        self.altitude_label = QtWidgets.QLabel(self.tab_1)
        self.altitude_label.setObjectName("altitude_label")
        self.verticalLayout_24.addWidget(self.altitude_label)
        self.pressure_label = QtWidgets.QLabel(self.tab_1)
        self.pressure_label.setObjectName("pressure_label")
        self.verticalLayout_24.addWidget(self.pressure_label)
        self.gridLayout_8.addLayout(self.verticalLayout_24, 1, 1, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_93 = QtWidgets.QLabel(self.tab_1)
        self.label_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_22.addWidget(self.label_93)
        self.label_94 = QtWidgets.QLabel(self.tab_1)
        self.label_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_22.addWidget(self.label_94)
        self.label_84 = QtWidgets.QLabel(self.tab_1)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_22.addWidget(self.label_84)
        self.gridLayout_8.addLayout(self.verticalLayout_22, 1, 2, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.delta_x_label = QtWidgets.QLabel(self.tab_1)
        self.delta_x_label.setObjectName("delta_x_label")
        self.verticalLayout_21.addWidget(self.delta_x_label)
        self.delta_y_label = QtWidgets.QLabel(self.tab_1)
        self.delta_y_label.setObjectName("delta_y_label")
        self.verticalLayout_21.addWidget(self.delta_y_label)
        self.resultant_label = QtWidgets.QLabel(self.tab_1)
        self.resultant_label.setObjectName("resultant_label")
        self.verticalLayout_21.addWidget(self.resultant_label)
        self.gridLayout_8.addLayout(self.verticalLayout_21, 1, 3, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_100 = QtWidgets.QLabel(self.tab_1)
        self.label_100.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_26.addWidget(self.label_100)
        self.label_104 = QtWidgets.QLabel(self.tab_1)
        self.label_104.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_26.addWidget(self.label_104)
        self.label_105 = QtWidgets.QLabel(self.tab_1)
        self.label_105.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_105.setObjectName("label_105")
        self.verticalLayout_26.addWidget(self.label_105)
        self.gridLayout_8.addLayout(self.verticalLayout_26, 1, 4, 1, 2)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.obstacle_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_label.setObjectName("obstacle_label")
        self.verticalLayout_25.addWidget(self.obstacle_label)
        self.obstacle_time_elapsed_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_time_elapsed_label.setObjectName("obstacle_time_elapsed_label")
        self.verticalLayout_25.addWidget(self.obstacle_time_elapsed_label)
        self.points_sec_label = QtWidgets.QLabel(self.tab_1)
        self.points_sec_label.setObjectName("points_sec_label")
        self.verticalLayout_25.addWidget(self.points_sec_label)
        self.gridLayout_8.addLayout(self.verticalLayout_25, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.gridLayout_13.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.temperature_label = QtWidgets.QLabel(self.tab_2)
        self.temperature_label.setObjectName("temperature_label")
        self.gridLayout_10.addWidget(self.temperature_label, 0, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.tab_2)
        self.label_108.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_108.setObjectName("label_108")
        self.gridLayout_10.addWidget(self.label_108, 0, 0, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.tab_2)
        self.label_109.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_109.setObjectName("label_109")
        self.gridLayout_10.addWidget(self.label_109, 1, 0, 1, 1)
        self.humiditity_label = QtWidgets.QLabel(self.tab_2)
        self.humiditity_label.setObjectName("humiditity_label")
        self.gridLayout_10.addWidget(self.humiditity_label, 1, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.bpm_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bpm_label.setFont(font)
        self.bpm_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bpm_label.setObjectName("bpm_label")
        self.verticalLayout_12.addWidget(self.bpm_label)
        self.label_113 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_113.setFont(font)
        self.label_113.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_113.setObjectName("label_113")
        self.verticalLayout_12.addWidget(self.label_113)
        self.gridLayout_11.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.body_presence_label = QtWidgets.QLabel(self.groupBox_5)
        self.body_presence_label.setObjectName("body_presence_label")
        self.gridLayout_11.addWidget(self.body_presence_label, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_6.setMinimumSize(QtCore.QSize(321, 221))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_11.addWidget(self.widget_6, 2, 0, 1, 2)
        self.label_124 = QtWidgets.QLabel(self.groupBox_5)
        self.label_124.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_124.setObjectName("label_124")
        self.gridLayout_11.addWidget(self.label_124, 1, 0, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.open_github_button = QtWidgets.QPushButton(self.tab)
        self.open_github_button.setObjectName("open_github_button")
        self.gridLayout.addWidget(self.open_github_button, 0, 0, 1, 1)
        self.open_website_button = QtWidgets.QPushButton(self.tab)
        self.open_website_button.setObjectName("open_website_button")
        self.gridLayout.addWidget(self.open_website_button, 1, 0, 1, 1)
        self.open_report_button = QtWidgets.QPushButton(self.tab)
        self.open_report_button.setObjectName("open_report_button")
        self.gridLayout.addWidget(self.open_report_button, 0, 1, 1, 1)
        self.open_data_button = QtWidgets.QPushButton(self.tab)
        self.open_data_button.setObjectName("open_data_button")
        self.gridLayout.addWidget(self.open_data_button, 1, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_118 = QtWidgets.QLabel(self.groupBox_7)
        self.label_118.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_118.setObjectName("label_118")
        self.gridLayout_16.addWidget(self.label_118, 0, 0, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.groupBox_7)
        self.label_119.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_119.setObjectName("label_119")
        self.gridLayout_16.addWidget(self.label_119, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_16.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_7)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_16.addWidget(self.dateTimeEdit, 1, 1, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_16)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.find_row_button = QtWidgets.QPushButton(self.groupBox_7)
        self.find_row_button.setObjectName("find_row_button")
        self.verticalLayout_13.addWidget(self.find_row_button)
        self.label_120 = QtWidgets.QLabel(self.groupBox_7)
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setWordWrap(True)
        self.label_120.setObjectName("label_120")
        self.verticalLayout_13.addWidget(self.label_120)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_14.addWidget(self.lineEdit_11)
        self.label_121 = QtWidgets.QLabel(self.groupBox_7)
        self.label_121.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_121.setObjectName("label_121")
        self.verticalLayout_14.addWidget(self.label_121)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_14.addWidget(self.pushButton_11, 0, 0, 1, 3)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_14.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.groupBox_6)
        self.label_107.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_107.setObjectName("label_107")
        self.gridLayout_14.addWidget(self.label_107, 1, 0, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.groupBox_6)
        self.label_106.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_106.setObjectName("label_106")
        self.gridLayout_14.addWidget(self.label_106, 2, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_14.addWidget(self.pushButton_17, 2, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_14.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_14.addWidget(self.pushButton_13, 1, 2, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.groupBox_6)
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.gridLayout_14.addWidget(self.label_122, 3, 0, 1, 3)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuLinks = QtWidgets.QMenu(self.menubar)
        self.menuLinks.setObjectName("menuLinks")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_Graph_Size = QtWidgets.QAction(MainWindow)
        self.actionChange_Graph_Size.setObjectName("actionChange_Graph_Size")
        self.actionChange_Read_Rate = QtWidgets.QAction(MainWindow)
        self.actionChange_Read_Rate.setObjectName("actionChange_Read_Rate")
        self.actionHERC_Guidebook = QtWidgets.QAction(MainWindow)
        self.actionHERC_Guidebook.setObjectName("actionHERC_Guidebook")
        self.actionObstacle_Task_Table = QtWidgets.QAction(MainWindow)
        self.actionObstacle_Task_Table.setObjectName("actionObstacle_Task_Table")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSettings.addAction(self.actionChange_Graph_Size)
        self.menuSettings.addAction(self.actionChange_Read_Rate)
        self.menuLinks.addAction(self.actionHERC_Guidebook)
        self.menuLinks.addSeparator()
        self.menuLinks.addAction(self.actionObstacle_Task_Table)
        self.menuLinks.addAction(self.actionGithub)
        self.menuLinks.addAction(self.actionWebsite)
        self.menuLinks.addAction(self.actionReport)
        self.menuLinks.addSeparator()
        self.menuLinks.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuLinks.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Currently pulling data from:"))
        self.global_source_label.setText(_translate("MainWindow", "Nothing"))
        self.label_22.setText(_translate("MainWindow", "Converted timestamp:"))
        self.global_cvtime_label.setText(_translate("MainWindow", "05/05/05 00:00:00"))
        self.label_24.setText(_translate("MainWindow", "Lag:"))
        self.global_lag_label.setText(_translate("MainWindow", "0s"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data Transfer: Socket"))
        self.connect_raspi_button.setText(_translate("MainWindow", "Connect to Raspberry Pi"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Port"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.socket_def_save_button.setText(_translate("MainWindow", "Save Default Values (all)"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter IP (198.168.1.76)"))
        self.socket_def_use_button.setText(_translate("MainWindow", "Use Default Values (all)"))
        self.label.setText(_translate("MainWindow", "Raspberry Pi:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Transfer: Google Sheets"))
        self.connect_gsheets_button.setText(_translate("MainWindow", "Read from Google Sheets"))
        self.label_6.setText(_translate("MainWindow", "Range:"))
        self.label_5.setText(_translate("MainWindow", "Spreadsheet ID:"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter a valid range"))
        self.label_7.setText(_translate("MainWindow", "Start from row:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "1 - infinity"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter spreadsheet ID (not the link)"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Read from Database File"))
        self.open_db_button.setText(_translate("MainWindow", "Open .db"))
        self.connect_db_button.setText(_translate("MainWindow", "Start Reading"))
        self.label_8.setText(_translate("MainWindow", "File path:"))
        self.label_10.setText(_translate("MainWindow", "Start from row:"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "The database\'s file path will be displayed here once selected"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "1 - infinity"))
        self.label_15.setText(_translate("MainWindow", "last_read = "))
        self.label_16.setText(_translate("MainWindow", "failed_attempts = "))
        self.last_read_label.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "len(queue) = "))
        self.queue_size_label.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Currently reading:"))
        self.lag_time_label.setText(_translate("MainWindow", "0s"))
        self.label_12.setText(_translate("MainWindow", "Lag time:"))
        self.reading_label.setText(_translate("MainWindow", "line ... with timestamp ..."))
        self.failed_attempts_label.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "heal_attempts = "))
        self.heal_attempts_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Data Source"))
        self.label_26.setText(_translate("MainWindow", "Status: Not Uploading"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Active Uploading"))
        self.pushButton_7.setText(_translate("MainWindow", "Start pushing data to AWS"))
        self.pushButton_8.setText(_translate("MainWindow", "Start pushing data to Google Sheets"))
        self.label_28.setText(_translate("MainWindow", "Append live data to the above sources as it comes in. Applies only to Socket connections."))
        self.label_29.setText(_translate("MainWindow", "Upload data every:"))
        self.label_30.setText(_translate("MainWindow", "second(s)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Batch Uploading"))
        self.pushButton_19.setText(_translate("MainWindow", "Push data to AWS"))
        self.pushButton_20.setText(_translate("MainWindow", "Push data to Google Sheets"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Settings"))
        self.label_34.setText(_translate("MainWindow", "Current data source: none"))
        self.label_31.setText(_translate("MainWindow", "Start writing from row:"))
        self.radioButton_2.setText(_translate("MainWindow", "Overwrite"))
        self.radioButton.setText(_translate("MainWindow", "Append"))
        self.label_32.setText(_translate("MainWindow", "Start reading from row:"))
        self.label_33.setText(_translate("MainWindow", "to row:"))
        self.label_27.setText(_translate("MainWindow", "Write Method"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Data Uploading"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "NEO-6M/GPS (Absolute)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Displacement (Relative)"))
        self.label_49.setText(_translate("MainWindow", "Overall"))
        self.label_50.setText(_translate("MainWindow", "This Read"))
        self.label_75.setText(_translate("MainWindow", "HDOP:"))
        self.label_128.setText(_translate("MainWindow", "Satellite count:"))
        self.label_37.setText(_translate("MainWindow", "Vectors measured:"))
        self.label_42.setText(_translate("MainWindow", "Distance traveled:"))
        self.hdop_label.setText(_translate("MainWindow", "123.1234567"))
        self.satellite_label.setText(_translate("MainWindow", "TextLabel"))
        self.total_vectors_label.setText(_translate("MainWindow", "TextLabel"))
        self.total_distance_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "Vectors measured:"))
        self.label_36.setText(_translate("MainWindow", "Distance traveled:"))
        self.label_46.setText(_translate("MainWindow", "Instantaneous speed:"))
        self.label_47.setText(_translate("MainWindow", "Moving average speed:"))
        self.this_read_vectors_label.setText(_translate("MainWindow", "123.1234567"))
        self.this_read_distance_label.setText(_translate("MainWindow", "TextLabel"))
        self.instantaneous_speed_label.setText(_translate("MainWindow", "TextLabel"))
        self.moving_average_speed_label.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "More GPS Data"))
        self.label_43.setText(_translate("MainWindow", "Pitch"))
        self.label_41.setText(_translate("MainWindow", "Roll"))
        self.label_51.setText(_translate("MainWindow", "Yaw"))
        self.pitch_label.setText(_translate("MainWindow", "TextLabel"))
        self.roll_label.setText(_translate("MainWindow", "TextLabel"))
        self.yaw_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_55.setText(_translate("MainWindow", "future orientation representation goes here"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Orientation"))
        self.section_label.setText(_translate("MainWindow", "14.1"))
        self.page_label.setText(_translate("MainWindow", "20"))
        self.label_95.setText(_translate("MainWindow", "Section"))
        self.label_96.setText(_translate("MainWindow", "Page"))
        self.obstacle_full_name_label.setText(_translate("MainWindow", "Solid Soil Sample Retrieval"))
        self.open_obstacles_button.setText(_translate("MainWindow", "Open Obstacle/Task Table"))
        self.obstacle_label_large.setText(_translate("MainWindow", "Task 1"))
        self.open_guidebook_button.setText(_translate("MainWindow", "Open HERC Guidebook"))
        self.obstacle_point_value_label.setText(_translate("MainWindow", "10 points maximum"))
        self.label_86.setText(_translate("MainWindow", "Latitude:"))
        self.label_74.setText(_translate("MainWindow", "Longitude:"))
        self.label_114.setText(_translate("MainWindow", "Altitude:"))
        self.label_116.setText(_translate("MainWindow", "Pressure:"))
        self.latitude_label.setText(_translate("MainWindow", "123.1234567"))
        self.longitude_label.setText(_translate("MainWindow", "123.1234567"))
        self.altitude_label.setText(_translate("MainWindow", "123m"))
        self.pressure_label.setText(_translate("MainWindow", "80000 Pa"))
        self.label_93.setText(_translate("MainWindow", "ΣΔx ="))
        self.label_94.setText(_translate("MainWindow", "ΣΔy ="))
        self.label_84.setText(_translate("MainWindow", "V_R ="))
        self.delta_x_label.setText(_translate("MainWindow", "152.15m (-2.8)"))
        self.delta_y_label.setText(_translate("MainWindow", "152.15m (-2.8)"))
        self.resultant_label.setText(_translate("MainWindow", "1234.56m @ 152.8 deg"))
        self.label_100.setText(_translate("MainWindow", "Currently Attempting:"))
        self.label_104.setText(_translate("MainWindow", "Time elapsed (task):"))
        self.label_105.setText(_translate("MainWindow", "Max points/second:"))
        self.obstacle_label.setText(_translate("MainWindow", "Task 1"))
        self.obstacle_time_elapsed_label.setText(_translate("MainWindow", "0:30"))
        self.points_sec_label.setText(_translate("MainWindow", "4.4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Positioning/Competition Data"))
        self.temperature_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_108.setText(_translate("MainWindow", "Temperature:"))
        self.label_109.setText(_translate("MainWindow", "Relative Humidity:"))
        self.humiditity_label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Athlete/Fitbit Data"))
        self.bpm_label.setText(_translate("MainWindow", "100"))
        self.label_113.setText(_translate("MainWindow", "BPM"))
        self.body_presence_label.setText(_translate("MainWindow", "Body currently present on Fitbit."))
        self.label_124.setText(_translate("MainWindow", "Heartrate Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Environmental Data"))
        self.open_github_button.setText(_translate("MainWindow", "Open GitHub"))
        self.open_website_button.setText(_translate("MainWindow", "Open Website"))
        self.open_report_button.setText(_translate("MainWindow", "Open Report"))
        self.open_data_button.setText(_translate("MainWindow", "Open Data Spreadsheet"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Timestamp Conversion"))
        self.label_118.setText(_translate("MainWindow", "UNIX timestamp:"))
        self.label_119.setText(_translate("MainWindow", "Human-readable:"))
        self.find_row_button.setText(_translate("MainWindow", "Find Equivalent Row"))
        self.label_120.setText(_translate("MainWindow", "If reading data from a database file or Google Sheets, you can use this button to try and find the relevant row."))
        self.label_121.setText(_translate("MainWindow", "Row"))
        self.label_11.setText(_translate("MainWindow", "Input:"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Streaming"))
        self.pushButton_11.setText(_translate("MainWindow", "Open Stream Overlay"))
        self.label_107.setText(_translate("MainWindow", "Livestream Address (LAN):"))
        self.label_106.setText(_translate("MainWindow", "Stream Key:"))
        self.pushButton_17.setText(_translate("MainWindow", "Read Last Values"))
        self.pushButton_13.setText(_translate("MainWindow", "Save Values"))
        self.label_122.setText(_translate("MainWindow", "For more livestream information, open the stream overlay."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Streaming/Utilities"))
        self.groupBox.setTitle(_translate("MainWindow", "Log"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuLinks.setTitle(_translate("MainWindow", "Links/About"))
        self.actionChange_Graph_Size.setText(_translate("MainWindow", "Change Graph Size"))
        self.actionChange_Read_Rate.setText(_translate("MainWindow", "Change Read Rate"))
        self.actionHERC_Guidebook.setText(_translate("MainWindow", "HERC Guidebook"))
        self.actionObstacle_Task_Table.setText(_translate("MainWindow", "Obstacle/Task Table"))
        self.actionGithub.setText(_translate("MainWindow", "GitHub"))
        self.actionWebsite.setText(_translate("MainWindow", "Website"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
