# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tinlo45501\Desktop\new2020.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 781, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 751, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(230, 31, 81, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(230, 62, 81, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(320, 30, 151, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 60, 151, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 28, 231, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 58, 231, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 751, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 30, 181, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(210, 31, 101, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(230, 62, 81, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 30, 421, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 60, 191, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(520, 62, 91, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(620, 60, 121, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 230, 751, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 20, 181, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(210, 31, 101, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 30, 421, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(220, 62, 91, 16))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 60, 421, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 60, 181, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 340, 111, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.reading_label = QtWidgets.QLabel(self.tab_4)
        self.reading_label.setGeometry(QtCore.QRect(130, 340, 171, 16))
        self.reading_label.setObjectName("reading_label")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 360, 111, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lag_time_label = QtWidgets.QLabel(self.tab_4)
        self.lag_time_label.setGeometry(QtCore.QRect(130, 360, 171, 16))
        self.lag_time_label.setObjectName("lag_time_label")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(320, 340, 111, 16))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(320, 360, 111, 16))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(570, 340, 111, 16))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(570, 360, 111, 16))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.queue_size_label = QtWidgets.QLabel(self.tab_4)
        self.queue_size_label.setGeometry(QtCore.QRect(440, 340, 121, 16))
        self.queue_size_label.setObjectName("queue_size_label")
        self.last_read_label = QtWidgets.QLabel(self.tab_4)
        self.last_read_label.setGeometry(QtCore.QRect(440, 360, 121, 16))
        self.last_read_label.setObjectName("last_read_label")
        self.failed_attempts_label = QtWidgets.QLabel(self.tab_4)
        self.failed_attempts_label.setGeometry(QtCore.QRect(690, 340, 71, 16))
        self.failed_attempts_label.setObjectName("failed_attempts_label")
        self.heal_attempts_label = QtWidgets.QLabel(self.tab_4)
        self.heal_attempts_label.setGeometry(QtCore.QRect(690, 360, 71, 16))
        self.heal_attempts_label.setObjectName("heal_attempts_label")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(4, 0, 771, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 40, 761, 121))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 331, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 20, 331, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setGeometry(QtCore.QRect(120, 70, 511, 20))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(230, 91, 111, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(350, 90, 81, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(440, 91, 111, 16))
        self.label_30.setObjectName("label_30")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 160, 761, 231))
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 30, 331, 51))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 90, 331, 51))
        self.pushButton_20.setObjectName("pushButton_20")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(350, 40, 391, 111))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(240, 50, 55, 16))
        self.label_33.setObjectName("label_33")
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setGeometry(QtCore.QRect(10, 80, 141, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 80, 81, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_15.setGeometry(QtCore.QRect(290, 50, 81, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 15, 199, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_13.setGeometry(QtCore.QRect(150, 49, 81, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_27 = QtWidgets.QLabel(self.groupBox_10)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.groupBox_10)
        self.label_31.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.label_31.setObjectName("label_31")
        self.label_34 = QtWidgets.QLabel(self.groupBox_9)
        self.label_34.setGeometry(QtCore.QRect(350, 20, 381, 20))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_1)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 541, 271))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_3 = QtWidgets.QWidget(self.tab_5)
        self.widget_3.setGeometry(QtCore.QRect(24, 0, 482, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(20, 40, 141, 191))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_75 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_27.addWidget(self.label_75)
        self.label_128 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_128.setObjectName("label_128")
        self.verticalLayout_27.addWidget(self.label_128)
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_27.addWidget(self.label_37)
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_27.addWidget(self.label_42)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(160, 40, 111, 191))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.hdop_label = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.hdop_label.setObjectName("hdop_label")
        self.verticalLayout_28.addWidget(self.hdop_label)
        self.satellite_label = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.satellite_label.setObjectName("satellite_label")
        self.verticalLayout_28.addWidget(self.satellite_label)
        self.total_vectors_label = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.total_vectors_label.setObjectName("total_vectors_label")
        self.verticalLayout_28.addWidget(self.total_vectors_label)
        self.total_distance_label = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.total_distance_label.setObjectName("total_distance_label")
        self.verticalLayout_28.addWidget(self.total_distance_label)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(280, 40, 141, 191))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_29.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_29.addWidget(self.label_36)
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_29.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_29.addWidget(self.label_47)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(420, 40, 111, 191))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.this_read_vectors_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.this_read_vectors_label.setObjectName("this_read_vectors_label")
        self.verticalLayout_30.addWidget(self.this_read_vectors_label)
        self.this_read_distance_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.this_read_distance_label.setObjectName("this_read_distance_label")
        self.verticalLayout_30.addWidget(self.this_read_distance_label)
        self.instantaneous_speed_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.instantaneous_speed_label.setObjectName("instantaneous_speed_label")
        self.verticalLayout_30.addWidget(self.instantaneous_speed_label)
        self.moving_average_speed_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.moving_average_speed_label.setObjectName("moving_average_speed_label")
        self.verticalLayout_30.addWidget(self.moving_average_speed_label)
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setGeometry(QtCore.QRect(100, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_7)
        self.label_50.setGeometry(QtCore.QRect(360, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_8)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 81, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_43.setObjectName("label_43")
        self.verticalLayout.addWidget(self.label_43)
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.verticalLayout.addWidget(self.label_41)
        self.label_51 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_51.setObjectName("label_51")
        self.verticalLayout.addWidget(self.label_51)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_8)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 10, 81, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pitch_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pitch_label.setObjectName("pitch_label")
        self.verticalLayout_2.addWidget(self.pitch_label)
        self.roll_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.roll_label.setObjectName("roll_label")
        self.verticalLayout_2.addWidget(self.roll_label)
        self.yaw_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.yaw_label.setObjectName("yaw_label")
        self.verticalLayout_2.addWidget(self.yaw_label)
        self.widget_4 = QtWidgets.QWidget(self.tab_8)
        self.widget_4.setGeometry(QtCore.QRect(180, 10, 341, 221))
        self.widget_4.setObjectName("widget_4")
        self.label_55 = QtWidgets.QLabel(self.widget_4)
        self.label_55.setGeometry(QtCore.QRect(100, 80, 131, 61))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_1)
        self.graphicsView_2.setGeometry(QtCore.QRect(550, 20, 50, 50))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 280, 81, 101))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_86 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_19.addWidget(self.label_86)
        self.label_74 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_19.addWidget(self.label_74)
        self.label_114 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_114.setObjectName("label_114")
        self.verticalLayout_19.addWidget(self.label_114)
        self.label_116 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_116.setObjectName("label_116")
        self.verticalLayout_19.addWidget(self.label_116)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_9.setGeometry(QtCore.QRect(550, 150, 191, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(650, 190, 91, 80))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.section_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.section_label.setObjectName("section_label")
        self.verticalLayout_20.addWidget(self.section_label)
        self.page_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.page_label.setObjectName("page_label")
        self.verticalLayout_20.addWidget(self.page_label)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(250, 280, 231, 101))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.delta_x_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.delta_x_label.setObjectName("delta_x_label")
        self.verticalLayout_21.addWidget(self.delta_x_label)
        self.delta_y_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.delta_y_label.setObjectName("delta_y_label")
        self.verticalLayout_21.addWidget(self.delta_y_label)
        self.resultant_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.resultant_label.setObjectName("resultant_label")
        self.verticalLayout_21.addWidget(self.resultant_label)
        self.obstacle_full_name_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_full_name_label.setGeometry(QtCore.QRect(550, 80, 191, 21))
        self.obstacle_full_name_label.setObjectName("obstacle_full_name_label")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_10.setGeometry(QtCore.QRect(550, 120, 191, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(210, 280, 41, 101))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_93 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_22.addWidget(self.label_93)
        self.label_94 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_22.addWidget(self.label_94)
        self.label_84 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_22.addWidget(self.label_84)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(550, 190, 91, 80))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_95 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_23.addWidget(self.label_95)
        self.label_96 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_23.addWidget(self.label_96)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(90, 280, 111, 101))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.latitude_label = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.latitude_label.setObjectName("latitude_label")
        self.verticalLayout_24.addWidget(self.latitude_label)
        self.longitude_label = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.longitude_label.setObjectName("longitude_label")
        self.verticalLayout_24.addWidget(self.longitude_label)
        self.altitude_label = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.altitude_label.setObjectName("altitude_label")
        self.verticalLayout_24.addWidget(self.altitude_label)
        self.pressure_label = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.pressure_label.setObjectName("pressure_label")
        self.verticalLayout_24.addWidget(self.pressure_label)
        self.obstacle_label_large = QtWidgets.QLabel(self.tab_1)
        self.obstacle_label_large.setGeometry(QtCore.QRect(610, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.obstacle_label_large.setFont(font)
        self.obstacle_label_large.setAlignment(QtCore.Qt.AlignCenter)
        self.obstacle_label_large.setObjectName("obstacle_label_large")
        self.obstacle_point_value_label = QtWidgets.QLabel(self.tab_1)
        self.obstacle_point_value_label.setGeometry(QtCore.QRect(550, 100, 191, 21))
        self.obstacle_point_value_label.setObjectName("obstacle_point_value_label")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(630, 280, 111, 101))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.obstacle_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.obstacle_label.setObjectName("obstacle_label")
        self.verticalLayout_25.addWidget(self.obstacle_label)
        self.obstacle_time_elapsed_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.obstacle_time_elapsed_label.setObjectName("obstacle_time_elapsed_label")
        self.verticalLayout_25.addWidget(self.obstacle_time_elapsed_label)
        self.points_sec_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.points_sec_label.setObjectName("points_sec_label")
        self.verticalLayout_25.addWidget(self.points_sec_label)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(490, 280, 141, 101))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_100 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_26.addWidget(self.label_100)
        self.label_104 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_26.addWidget(self.label_104)
        self.label_105 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_105.setObjectName("label_105")
        self.verticalLayout_26.addWidget(self.label_105)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_108 = QtWidgets.QLabel(self.tab_2)
        self.label_108.setGeometry(QtCore.QRect(450, 10, 91, 16))
        self.label_108.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_108.setObjectName("label_108")
        self.label_109 = QtWidgets.QLabel(self.tab_2)
        self.label_109.setGeometry(QtCore.QRect(430, 40, 111, 16))
        self.label_109.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_109.setObjectName("label_109")
        self.temperature_label = QtWidgets.QLabel(self.tab_2)
        self.temperature_label.setGeometry(QtCore.QRect(550, 10, 55, 16))
        self.temperature_label.setObjectName("temperature_label")
        self.humiditity_label = QtWidgets.QLabel(self.tab_2)
        self.humiditity_label.setGeometry(QtCore.QRect(550, 40, 55, 16))
        self.humiditity_label.setObjectName("humiditity_label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 70, 321, 321))
        self.groupBox_5.setObjectName("groupBox_5")
        self.bpm_label = QtWidgets.QLabel(self.groupBox_5)
        self.bpm_label.setGeometry(QtCore.QRect(20, 20, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bpm_label.setFont(font)
        self.bpm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bpm_label.setObjectName("bpm_label")
        self.label_113 = QtWidgets.QLabel(self.groupBox_5)
        self.label_113.setGeometry(QtCore.QRect(21, 67, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_113.setFont(font)
        self.label_113.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_113.setObjectName("label_113")
        self.body_presence_label = QtWidgets.QLabel(self.groupBox_5)
        self.body_presence_label.setGeometry(QtCore.QRect(100, 54, 231, 16))
        self.body_presence_label.setObjectName("body_presence_label")
        self.widget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_6.setGeometry(QtCore.QRect(10, 100, 321, 221))
        self.widget_6.setObjectName("widget_6")
        self.label_124 = QtWidgets.QLabel(self.groupBox_5)
        self.label_124.setGeometry(QtCore.QRect(14, 90, 321, 20))
        self.label_124.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_124.setObjectName("label_124")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 411, 381))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 220, 761, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 20, 741, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_17.setGeometry(QtCore.QRect(520, 110, 221, 25))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_107 = QtWidgets.QLabel(self.groupBox_6)
        self.label_107.setGeometry(QtCore.QRect(10, 84, 161, 16))
        self.label_107.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_107.setObjectName("label_107")
        self.label_106 = QtWidgets.QLabel(self.groupBox_6)
        self.label_106.setGeometry(QtCore.QRect(10, 112, 161, 16))
        self.label_106.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_106.setObjectName("label_106")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 82, 331, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 110, 331, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 81, 221, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_122 = QtWidgets.QLabel(self.groupBox_6)
        self.label_122.setGeometry(QtCore.QRect(10, 140, 751, 20))
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 110, 761, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_7)
        self.dateTimeEdit.setGeometry(QtCore.QRect(130, 58, 194, 22))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_118 = QtWidgets.QLabel(self.groupBox_7)
        self.label_118.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.label_118.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_118.setObjectName("label_118")
        self.label_119 = QtWidgets.QLabel(self.groupBox_7)
        self.label_119.setGeometry(QtCore.QRect(10, 58, 111, 20))
        self.label_119.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_119.setObjectName("label_119")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 30, 194, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_12.setGeometry(QtCore.QRect(350, 27, 241, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_120 = QtWidgets.QLabel(self.groupBox_7)
        self.label_120.setGeometry(QtCore.QRect(350, 54, 241, 51))
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setWordWrap(True)
        self.label_120.setObjectName("label_120")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(623, 30, 91, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_121 = QtWidgets.QLabel(self.groupBox_7)
        self.label_121.setGeometry(QtCore.QRect(640, 50, 55, 16))
        self.label_121.setAlignment(QtCore.Qt.AlignCenter)
        self.label_121.setObjectName("label_121")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 460, 791, 121))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 781, 91))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 6, 161, 16))
        self.label_3.setObjectName("label_3")
        self.global_source_label = QtWidgets.QLabel(self.centralwidget)
        self.global_source_label.setGeometry(QtCore.QRect(180, 6, 121, 16))
        self.global_source_label.setObjectName("global_source_label")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(310, 6, 131, 16))
        self.label_22.setObjectName("label_22")
        self.global_cvtime_label = QtWidgets.QLabel(self.centralwidget)
        self.global_cvtime_label.setGeometry(QtCore.QRect(450, 6, 131, 16))
        self.global_cvtime_label.setObjectName("global_cvtime_label")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(620, 6, 31, 16))
        self.label_24.setObjectName("label_24")
        self.global_lag_label = QtWidgets.QLabel(self.centralwidget)
        self.global_lag_label.setGeometry(QtCore.QRect(660, 6, 31, 16))
        self.global_lag_label.setObjectName("global_lag_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuLinks = QtWidgets.QMenu(self.menubar)
        self.menuLinks.setObjectName("menuLinks")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_Graph_Size = QtWidgets.QAction(MainWindow)
        self.actionChange_Graph_Size.setObjectName("actionChange_Graph_Size")
        self.actionChange_Read_Rate = QtWidgets.QAction(MainWindow)
        self.actionChange_Read_Rate.setObjectName("actionChange_Read_Rate")
        self.actionHERC_Guidebook = QtWidgets.QAction(MainWindow)
        self.actionHERC_Guidebook.setObjectName("actionHERC_Guidebook")
        self.actionObstacle_Task_Table = QtWidgets.QAction(MainWindow)
        self.actionObstacle_Task_Table.setObjectName("actionObstacle_Task_Table")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSettings.addAction(self.actionChange_Graph_Size)
        self.menuSettings.addAction(self.actionChange_Read_Rate)
        self.menuLinks.addAction(self.actionHERC_Guidebook)
        self.menuLinks.addSeparator()
        self.menuLinks.addAction(self.actionObstacle_Task_Table)
        self.menuLinks.addAction(self.actionGithub)
        self.menuLinks.addAction(self.actionWebsite)
        self.menuLinks.addAction(self.actionReport)
        self.menuLinks.addSeparator()
        self.menuLinks.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuLinks.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data Transfer: Socket"))
        self.pushButton.setText(_translate("MainWindow", "Connect to Raspberry Pi"))
        self.label.setText(_translate("MainWindow", "Raspberry Pi:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter IP (198.168.1.76)"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Port"))
        self.pushButton_2.setText(_translate("MainWindow", "Use Default Values (all)"))
        self.pushButton_3.setText(_translate("MainWindow", "Save Default Values (all)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Transfer: Google Sheets"))
        self.pushButton_4.setText(_translate("MainWindow", "Read from Google Sheets"))
        self.label_5.setText(_translate("MainWindow", "Spreadsheet ID:"))
        self.label_6.setText(_translate("MainWindow", "Range:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter spreadsheet ID (not the link)"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter a valid range"))
        self.label_7.setText(_translate("MainWindow", "Start from row:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "1 - infinity"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Read from Database File"))
        self.pushButton_5.setText(_translate("MainWindow", "Open .db"))
        self.label_8.setText(_translate("MainWindow", "File path:"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "The database\'s file path will be displayed here once selected"))
        self.label_10.setText(_translate("MainWindow", "Start from row:"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "1 - infinity"))
        self.pushButton_6.setText(_translate("MainWindow", "Start Reading"))
        self.label_9.setText(_translate("MainWindow", "Currently reading:"))
        self.reading_label.setText(_translate("MainWindow", "line ... with timestamp ..."))
        self.label_12.setText(_translate("MainWindow", "Lag time:"))
        self.lag_time_label.setText(_translate("MainWindow", "0s"))
        self.label_14.setText(_translate("MainWindow", "len(queue) = "))
        self.label_15.setText(_translate("MainWindow", "last_read = "))
        self.label_16.setText(_translate("MainWindow", "failed_attempts = "))
        self.label_17.setText(_translate("MainWindow", "heal_attempts = "))
        self.queue_size_label.setText(_translate("MainWindow", "0"))
        self.last_read_label.setText(_translate("MainWindow", "0"))
        self.failed_attempts_label.setText(_translate("MainWindow", "0"))
        self.heal_attempts_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Data Source"))
        self.label_26.setText(_translate("MainWindow", "Status: Not Uploading"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Active Uploading"))
        self.pushButton_7.setText(_translate("MainWindow", "Start pushing data to AWS"))
        self.pushButton_8.setText(_translate("MainWindow", "Start pushing data to Google Sheets"))
        self.label_28.setText(_translate("MainWindow", "Append live data to the above sources as it comes in. Applies only to Socket connections."))
        self.label_29.setText(_translate("MainWindow", "Upload data every:"))
        self.label_30.setText(_translate("MainWindow", "second(s)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Batch Uploading"))
        self.pushButton_19.setText(_translate("MainWindow", "Push data to AWS"))
        self.pushButton_20.setText(_translate("MainWindow", "Push data to Google Sheets"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Settings"))
        self.label_33.setText(_translate("MainWindow", "to row:"))
        self.label_32.setText(_translate("MainWindow", "Start reading from row:"))
        self.radioButton_2.setText(_translate("MainWindow", "Overwrite"))
        self.radioButton.setText(_translate("MainWindow", "Append"))
        self.label_27.setText(_translate("MainWindow", "Write Method"))
        self.label_31.setText(_translate("MainWindow", "Start writing from row:"))
        self.label_34.setText(_translate("MainWindow", "Current data source: none"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Data Uploading"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "NEO-6M/GPS (Absolute)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Displacement (Relative)"))
        self.label_75.setText(_translate("MainWindow", "HDOP:"))
        self.label_128.setText(_translate("MainWindow", "Satellite count:"))
        self.label_37.setText(_translate("MainWindow", "Vectors measured:"))
        self.label_42.setText(_translate("MainWindow", "Distance traveled:"))
        self.hdop_label.setText(_translate("MainWindow", "123.1234567"))
        self.satellite_label.setText(_translate("MainWindow", "TextLabel"))
        self.total_vectors_label.setText(_translate("MainWindow", "TextLabel"))
        self.total_distance_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "Vectors measured:"))
        self.label_36.setText(_translate("MainWindow", "Distance traveled:"))
        self.label_46.setText(_translate("MainWindow", "Instantaneous speed:"))
        self.label_47.setText(_translate("MainWindow", "Moving average speed:"))
        self.this_read_vectors_label.setText(_translate("MainWindow", "123.1234567"))
        self.this_read_distance_label.setText(_translate("MainWindow", "TextLabel"))
        self.instantaneous_speed_label.setText(_translate("MainWindow", "TextLabel"))
        self.moving_average_speed_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "Overall"))
        self.label_50.setText(_translate("MainWindow", "This Read"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "More GPS Data"))
        self.label_43.setText(_translate("MainWindow", "Pitch"))
        self.label_41.setText(_translate("MainWindow", "Roll"))
        self.label_51.setText(_translate("MainWindow", "Yaw"))
        self.pitch_label.setText(_translate("MainWindow", "TextLabel"))
        self.roll_label.setText(_translate("MainWindow", "TextLabel"))
        self.yaw_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_55.setText(_translate("MainWindow", "future orientation representation goes here"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Orientation"))
        self.label_86.setText(_translate("MainWindow", "Latitude:"))
        self.label_74.setText(_translate("MainWindow", "Longitude:"))
        self.label_114.setText(_translate("MainWindow", "Altitude:"))
        self.label_116.setText(_translate("MainWindow", "Pressure:"))
        self.pushButton_9.setText(_translate("MainWindow", "Open HERC Guidebook"))
        self.section_label.setText(_translate("MainWindow", "14.1"))
        self.page_label.setText(_translate("MainWindow", "20"))
        self.delta_x_label.setText(_translate("MainWindow", "152.15m (-2.8)"))
        self.delta_y_label.setText(_translate("MainWindow", "152.15m (-2.8)"))
        self.resultant_label.setText(_translate("MainWindow", "1234.56m @ 152.8 deg"))
        self.obstacle_full_name_label.setText(_translate("MainWindow", "Solid Soil Sample Retrieval"))
        self.pushButton_10.setText(_translate("MainWindow", "Open Obstacle/Task Table"))
        self.label_93.setText(_translate("MainWindow", "ΣΔx ="))
        self.label_94.setText(_translate("MainWindow", "ΣΔy ="))
        self.label_84.setText(_translate("MainWindow", "V_R ="))
        self.label_95.setText(_translate("MainWindow", "Section"))
        self.label_96.setText(_translate("MainWindow", "Page"))
        self.latitude_label.setText(_translate("MainWindow", "123.1234567"))
        self.longitude_label.setText(_translate("MainWindow", "123.1234567"))
        self.altitude_label.setText(_translate("MainWindow", "123m"))
        self.pressure_label.setText(_translate("MainWindow", "80000 Pa"))
        self.obstacle_label_large.setText(_translate("MainWindow", "Task 1"))
        self.obstacle_point_value_label.setText(_translate("MainWindow", "10 points maximum"))
        self.obstacle_label.setText(_translate("MainWindow", "Task 1"))
        self.obstacle_time_elapsed_label.setText(_translate("MainWindow", "0:30"))
        self.points_sec_label.setText(_translate("MainWindow", "4.4"))
        self.label_100.setText(_translate("MainWindow", "Currently Attempting:"))
        self.label_104.setText(_translate("MainWindow", "Time elapsed (task):"))
        self.label_105.setText(_translate("MainWindow", "Max points/second:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Positioning/Competition Data"))
        self.label_108.setText(_translate("MainWindow", "Temperature:"))
        self.label_109.setText(_translate("MainWindow", "Relative Humidity:"))
        self.temperature_label.setText(_translate("MainWindow", "TextLabel"))
        self.humiditity_label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Athlete/Fitbit Data"))
        self.bpm_label.setText(_translate("MainWindow", "100"))
        self.label_113.setText(_translate("MainWindow", "BPM"))
        self.body_presence_label.setText(_translate("MainWindow", "Body currently present on Fitbit."))
        self.label_124.setText(_translate("MainWindow", "Heartrate Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Environmental Data"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Streaming"))
        self.pushButton_11.setText(_translate("MainWindow", "Open Stream Overlay"))
        self.pushButton_17.setText(_translate("MainWindow", "Read Last Values"))
        self.label_107.setText(_translate("MainWindow", "Livestream Address (LAN):"))
        self.label_106.setText(_translate("MainWindow", "Stream Key:"))
        self.pushButton_13.setText(_translate("MainWindow", "Save Values"))
        self.label_122.setText(_translate("MainWindow", "For more livestream information, open the stream overlay."))
        self.groupBox_7.setTitle(_translate("MainWindow", "Timestamp Conversion"))
        self.label_118.setText(_translate("MainWindow", "UNIX timestamp:"))
        self.label_119.setText(_translate("MainWindow", "Human-readable:"))
        self.pushButton_12.setText(_translate("MainWindow", "Find Equivalent Row"))
        self.label_120.setText(_translate("MainWindow", "If reading data from a database file or Google Sheets, you can use this button to try and find the relevant row."))
        self.label_121.setText(_translate("MainWindow", "Row"))
        self.pushButton_14.setText(_translate("MainWindow", "Open GitHub"))
        self.pushButton_15.setText(_translate("MainWindow", "Open Website"))
        self.pushButton_16.setText(_translate("MainWindow", "Open Report"))
        self.pushButton_18.setText(_translate("MainWindow", "Open Data Spreadsheet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Streaming/Utilities"))
        self.groupBox.setTitle(_translate("MainWindow", "Log"))
        self.label_3.setText(_translate("MainWindow", "Currently pulling data from:"))
        self.global_source_label.setText(_translate("MainWindow", "Nothing"))
        self.label_22.setText(_translate("MainWindow", "Converted timestamp:"))
        self.global_cvtime_label.setText(_translate("MainWindow", "05/05/05 00:00:00"))
        self.label_24.setText(_translate("MainWindow", "Lag:"))
        self.global_lag_label.setText(_translate("MainWindow", "0s"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuLinks.setTitle(_translate("MainWindow", "Links/About"))
        self.actionChange_Graph_Size.setText(_translate("MainWindow", "Change Graph Size"))
        self.actionChange_Read_Rate.setText(_translate("MainWindow", "Change Read Rate"))
        self.actionHERC_Guidebook.setText(_translate("MainWindow", "HERC Guidebook"))
        self.actionObstacle_Task_Table.setText(_translate("MainWindow", "Obstacle/Task Table"))
        self.actionGithub.setText(_translate("MainWindow", "GitHub"))
        self.actionWebsite.setText(_translate("MainWindow", "Website"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

